apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pubg-ui
  name: pubg-ui
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: pubg-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pubg-ui
    spec:
      containers:
      - image: kumar1991/pubgui:v2
        imagePullPolicy: IfNotPresent
        name: pubg-ui
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pubg-ui
  name: pubg-ui
  namespace: default
spec:
  ports:
    - nodePort: 31478
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pubg-ui
  sessionAffinity: ClientIP
  type: LoadBalancer


